name       : ccid
version    : 1.4.27
release    : 3
source     :
    - https://alioth.debian.org/frs/download.php/latestfile/112/ccid-1.4.27.tar.bz2 : a660e269606986cb94840ad5ba802ffb0cd23dd12b98f69a35035e0deb9dd137
license    : LGPL-2.1
component  : programming
summary    : Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
description: |
    Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libusb-1.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-Yubikey-devices.patch
    %configure --enable-zlp
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 src/92_pcscd_ccid.rules $installdir/%libdir%/udev/rules.d/92_pcscd_ccid.rules
