name       : ccid
version    : 1.4.30
release    : 6
source     :
    - https://ccid.apdu.fr/files/ccid-1.4.30.tar.bz2 : ac17087be08880a0cdf99a8a2799a4ef004dc6ffa08b4d9b0ad995f39a53ff7c
license    : LGPL-2.1-or-later
component  : programming
summary    : Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
description: |
    Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libusb-1.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-Yubikey-devices.patch
    %configure --enable-zlp
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 src/92_pcscd_ccid.rules $installdir/%libdir%/udev/rules.d/92_pcscd_ccid.rules
