name       : ccid
version    : 1.4.25
release    : 1
source     :
    - https://alioth.debian.org/frs/download.php/latestfile/112/ccid-1.4.25.tar.bz2 : 6b062b4ce0f04d6838d58e6faa255ba05222bd8ecb57a2d1116fdbe22f253609
license    : LGPL-2.1
component  : programming
summary    : Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
description: |
    Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libusb-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 src/92_pcscd_ccid.rules $installdir/%libdir%/udev/rules.d/92_pcscd_ccid.rules
