name       : ccid
version    : 1.4.32
release    : 12
source     :
    - git|https://github.com/LudovicRousseau/CCID : ccid-1.4.32
license    : LGPL-2.1-or-later
component  : programming
summary    : Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver
description: |
    Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libusb-1.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-Yubikey-devices.patch
    ./bootstrap
    %configure --enable-zlp LEXLIB=
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 src/92_pcscd_ccid.rules $installdir/%libdir%/udev/rules.d/92_pcscd_ccid.rules
